### PR TITLE
Add discussion of alternative names for require and prefer.

### PR DESCRIPTION
**Pull request by chriskohlhoff**

### CODE REVIEW

**Comment by chriskohlhoff** [comment]
@AerialMantis can you please confirm that this concurs with the feedback at cppcon. Once you're happy with it then it should be ready for @jaredhoberock to merge.

**Comment by AerialMantis** [comment]
@chriskohlhoff yeah this looks good, there was also feedback that `transform` could conflict with the algorithm, so we could mention that as a consideration as well.

**Comment by chriskohlhoff** [comment]
Done. @jaredhoberock this one is ready to merge if you're happy with it.

**Comment by jaredhoberock** [comment]
LGTM. Thanks.

**Pull request merged**
