### PR TITLE
Changelog & metadata updates

### PR DESCRIPTION
**Pull request by jaredhoberock**
Since we added support for guaranteeing forward progress wrt the caller in R3, I think we need no longer suggest that this is an open design issue.

### CODE REVIEW

**Comment by jaredhoberock** [comment]
Updated the paper metadata & added a changelog.

**Comment by jaredhoberock** [comment]
@chriskohlhoff @AerialMantis @ccmysen, if you see this before tomorrow morning, take a quick look at the changelog and let me know if there are items I've missed that ought to be mentioned.

**Comment by chriskohlhoff** [comment]
I'd suggest changing:

> Introduced properties allowing executors to opt into one-way to two-way adaptations

to something like:

> Introduced properties allowing executors to opt into adaptations that add blocking semantics

**Comment by jaredhoberock** [comment]
Thanks, I've made that change and merged.

**Pull request merged**
